dbt_elt:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DATABASE') }}"
      host: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      type: redshift
      user: "{{ env_var('DBT_USER') }}"
  target: dev